const oneOnOnePrompts = [
    "What's one thing that would make your week better?",
    "What's been draining your energy lately?",
    "Is there anything blocking you right now that I could help clear?",
    "How do you feel about your current workload?",
    "What's something you learned recently that you're excited about?",
    "Is there a skill you'd like to grow?",
    "Is there a project or type of work you'd like more exposure to?",
    "How do you feel about the feedback you've been getting?",
    "Is there feedback you'd like to give me?",
    "What's one thing I could do differently to support you better?",
    "Do you feel like your contributions are recognized?",
    "How are things going with the rest of the team?",
    "Is there anyone on the team you'd like more time working with?",
    "What's one process or ceremony you'd change if you could?",
    "What's the biggest source of friction in your day-to-day work?",
    "How do you feel about the pace of the current sprint/project?",
    "Is there anything about the roadmap that's unclear or concerning?",
    "Is there a decision I made recently that you disagreed with?",
    "How's your work/life balance been lately?",
    "What's one thing outside of work that's been on your mind?",
    "Do you feel like you have enough autonomy in your work?",
    "What would make our 1:1s more useful to you?",
    "Is there a tool, process, or resource you're missing?",
    "What's something you wish leadership understood better?",
    "What is something that I should know about that I might not?",
    "What is a domain that you own that you should probably not renew?",
    "What is your favorite way to treat yourself?",
    "Is there an item with which you might need to ask for help, but have been hesitating to do so?",
    "What, if anything, did you used to do that you find you don’t have time for right now?",
    "What was the last thing at work that you got a lot of satisfaction from?",
    "What types of conflicts do you find most challenging to resolve?",
    "Where can I be delegating more?",
    "What shifts are you noticing in our environment, and how are they affecting you/the team/your work?",
    "What problems do you think we should solve in the upcoming months?",
    "Where are we spending time as a team that you don't think we shouldn't be focused on?",
    "What could we drop that we haven't yet?",
    "If you were to create your ideal position, how would it differ from what you are currently doing?",
    "How comfortable do you feel giving feedback to your peers?",
    "If I was in charge I would change ...",
    "What skills do you have that you think are underutilized?",
    "What area(s) should I be more/less involved in?",
    "Do you feel I am advocating for you too much/enough/not enough?",
    "Are there any conflicts in the team that you believe are impacting productivity?",
    "What makes you grumpy, how will I know, and how can I help?",
    "How do you prefer feedback? (Medium, Cadence, Visibility)",
    "What makes 1:1s the most valuable for you?"
];
